
import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { Resend } from "npm:resend@2.0.0";

const resend = new Resend(Deno.env.get("RESEND_API_KEY"));

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
};

interface WithdrawalEmailRequest {
  userEmail: string;
  userId: string;
  method: string;
  number: string;
  coins: number;
  payout: string;
}

const handler = async (req: Request): Promise<Response> => {
  // Handle CORS preflight requests
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { userEmail, userId, method, number, coins, payout }: WithdrawalEmailRequest = await req.json();

    const methodDisplay = method === 'paytm' ? 'Paytm/UPI' : 'Bank Account';

    const emailResponse = await resend.emails.send({
      from: "VideoTube <noreply@resend.dev>",
      to: ["themoneytubeteam@gmail.com"],
      subject: `Withdrawal Request from ${userEmail}`,
      html: `
        <h2>New Withdrawal Request</h2>
        <p>A user has requested a withdrawal from VideoTube.</p>
        
        <h3>Request Details:</h3>
        <ul>
          <li><strong>User Email:</strong> ${userEmail}</li>
          <li><strong>User ID:</strong> ${userId}</li>
          <li><strong>Payment Method:</strong> ${methodDisplay}</li>
          <li><strong>Number:</strong> ${number}</li>
          <li><strong>Coins to Withdraw:</strong> ${coins}</li>
          <li><strong>Expected Payout:</strong> ₹${payout}</li>
        </ul>
        
        <p>Please process this request manually and confirm on the admin panel at:</p>
        <p><a href="https://your-app-url.com/999admin">Admin Panel</a></p>
        
        <hr>
        <p><small>This email was automatically generated by VideoTube withdrawal system.</small></p>
      `,
    });

    console.log("Withdrawal email sent successfully:", emailResponse);

    return new Response(JSON.stringify(emailResponse), {
      status: 200,
      headers: {
        "Content-Type": "application/json",
        ...corsHeaders,
      },
    });
  } catch (error: any) {
    console.error("Error in send-withdrawal-email function:", error);
    return new Response(
      JSON.stringify({ error: error.message }),
      {
        status: 500,
        headers: { "Content-Type": "application/json", ...corsHeaders },
      }
    );
  }
};

serve(handler);
