// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://idfziukuyvpoyxsglejt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlkZnppdWt1eXZwb3l4c2dsZWp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0OTE4MzksImV4cCI6MjA2NDA2NzgzOX0.ctiNzI7n2267qxqK8mERfWLvasIVYoauCuCqgkwZjW8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);